#my.datasource.url=local.db.com
#my.datasource.username=username
#my.datasource.password=password
#my.datasource.etc.max-connection=1
#my.datasource.etc.timeout=3500ms
#my.datasource.etc.options=CACHE,ADMIN
my:
  datasource:
    url: local.db.com
    username: username
    password: password
    etc:
      max-connection: 1
      timeout: 60s
      options: CACHE,ADMIN
---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username: dev_username
    password: dev_password
    etc:
      max-connection: 1
      timeout: 60s
      options: DEV,CACHE,ADMIN
---
spring:
  config:
    activate:
      on-profile: prod
my:
  datasource:
    url: prod.db.com
    username: prod_username
    password: prod_password
    etc:
      max-connection: 1
      timeout: 60s
      options: PROD,CACHE,ADMIN